-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-1", mode = "2560x1440@143.998", position = "0x0", scale = 1.25, transform = 1, vrr = 2, bitdepth = 10, cm = "hdr", sdrbrightness = 1.2, sdrsaturation = 0.9, supports_wide_color = true, supports_hdr = false, sdr_eotf = "gamma22", icc = [[/home/u/profile with spaces.icc]], sdr_min_luminance = 0.005, sdr_max_luminance = 200, min_luminance = 0.001, max_luminance = 1000, max_avg_luminance = 400 })
hl.monitor({ output = "HDMI-A-1", disabled = true })
hl.monitor({ output = 'desc:Dell Inc. DELL U2720Q ABC123', mode = "3840x2160@59.997", position = "2048x0", scale = 1.5, transform = 5, vrr = 1 })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "0x1152", scale = 1, mirror = "DP-1", vrr = 0 })
hl.monitor({ output = "DP-2", mode = "1920x1080@60.000", position = "-1920x0", scale = 1 })
hl.monitor({ output = "DP-3", position = "0x0", scale = 1, vrr = 2 })
hl.monitor({ output = "it's", mode = "1920x1080@60.000", position = "0x0", scale = 1 })
